language: go
sudo: false

go:
- 1.14.x

matrix:
  fast_finish: true

before_install:
- make init dep

script:
- make status verify

before_deploy:
- make status release
- echo "Deploying to GitHub releases ..."

deploy:
  provider: releases
  api_key:
    secure: ZtoUiICdperoWcnXLDYdlMP227imit75NAOXnranUernLtPOBaJ4N5OHIXkS7FXGPb4b3drsEuOGZ/jx+cRYBExxftD54teRPJIzsV1S9MmSP1BnLOfXeTV1ls4ckReDZzTCtIYohbno44S95SN2ds0s75P/Vqha/kLstfQJ+nrZCyzsvVTQRTUoN46eI0D3fA3HJXz+eZ4J+sLFd5JFp6ZrEvHomODbbuW47iG7pa2aOPBCjywlT2kDjJLQxg/5PJgIWwVtE90pBeGIgbI++dyNAXMw35+vtutGmIXTIhkTrKhrvYW/9+gvhZNZ8bLwvZ0hIsfrKherTmOWvsGSjkRp1AyORl7H9TEvQxq0nbb+MObpTS26p8j0NOOjsYHIXSIZV+msXtwAH2MYitTbnuAjBpvi0Ihye5ESZexQu8h+YP6HygdhJcSm6GlDYxw8Qv4Ec3gotYG6p55ZYjvIq4W8fR+cZKn1aTODF49XvEJXztjJw3sVXUeLV9QoitHffPAHnGrmwLPWQprioEOHo5gDvncathCa4G55D7r7hZPlB4n5m4wKb+8trM0AUk7Jxianpyo+tBMnF0Pxw3nOEEFrLeCOpdfAacsyhKUOGyBieqVV7dS+1XEghK1MwIjMwcCn3Ydzb5mi5keSh7u1mBCwplsZzjeJn11xaemxbeU=
  skip_cleanup: true
  on:
    repo: VirtusLab/render
    tags: true
  file:
  - cross/render-darwin-amd64
  - cross/render-darwin-amd64.md5
  - cross/render-darwin-amd64.sha256
  - cross/render-darwin-amd64.tar.gz
  - cross/render-darwin-386
  - cross/render-darwin-386.md5
  - cross/render-darwin-386.sha256
  - cross/render-darwin-386.tar.gz
  - cross/render-freebsd-amd64
  - cross/render-freebsd-amd64.md5
  - cross/render-freebsd-amd64.sha256
  - cross/render-freebsd-amd64.tar.gz
  - cross/render-freebsd-386
  - cross/render-freebsd-386.md5
  - cross/render-freebsd-386.sha256
  - cross/render-freebsd-386.tar.gz
  - cross/render-linux-arm
  - cross/render-linux-arm.md5
  - cross/render-linux-arm.sha256
  - cross/render-linux-arm.tar.gz
  - cross/render-linux-arm64
  - cross/render-linux-arm64.md5
  - cross/render-linux-arm64.sha256
  - cross/render-linux-arm64.tar.gz
  - cross/render-linux-amd64
  - cross/render-linux-amd64.md5
  - cross/render-linux-amd64.sha256
  - cross/render-linux-amd64.tar.gz
  - cross/render-linux-386
  - cross/render-linux-386.md5
  - cross/render-linux-386.sha256
  - cross/render-linux-386.tar.gz
  - cross/render-windows-amd64
  - cross/render-windows-amd64.md5
  - cross/render-windows-amd64.sha256
  - cross/render-windows-amd64.tar.gz
  - cross/render-windows-386
  - cross/render-windows-386.md5
  - cross/render-windows-386.sha256
  - cross/render-windows-386.tar.gz

cache:
  directories:
  - vendor

notifications:
  slack:
    secure: SDPUVbLgg9uye/9JRpjVLz/6Y9ykxVlGSpxDy3S8fBUOfjrp9MMe+yCnfAqphRNBGIo4DJQ40Ds/2DQPbCXHqJZcbvloEK0vxTghpFXkGZF7CLo/oy1yjfo4ezoCAxjuFgb6Af/uvO99Us07dp1LldzJxlI6bgPpI/1AWwKl+Ilv1f9ngQ0mzv1EZiwTbJsRdtgYa+qKcYVl040wZK3xy/6gZPx9JY8rh2nPY1ztbiVwvSicSb7O07Da7/e+T1HzlQ02JPNE0hh9gwRgUifPZ4p70vRdKLfHNevq+4k4Ws7P1eVJv+qCfHWIGikFSRzNpHO/X8kROERLtH4PGRHfgWXhcISWpLLr1GWlhO+hBRNCRIskBbuwd/z1WLLwuzeNpbC/a5Up3H2M4hIoYahC0GDd4C8w9oChrS+5PIKzdK6Y8Rx9royxiRudR7WZKBGT2t3u1d3DYpQ5q+iPKZ19Q5DLrJ4BbyjAZeh4rytr3OBkX1fNAe1RiNJdzPAz9R8CLSbEvYSEZsfGsBCuBzxhFgavOSYYeN3H/Ilh3wwmgYjiReIqztvGVaRATg+HAWCRWkh+QHj6KfOuvBJONzSNnAyXo8WuWSSe7d060ne912WbVOrnE+79/I6iA4r4oPN8QuWaI7yzIEnOMPcp3J9/WxJhZiOl4oePWAYXy55VntQ=
